export const REQUEST_LOGIN_USER = 'REQUEST_LOGIN_USER';
export const SUCCESS_LOGIN_USER = 'SUCCESS_LOGIN_USER';
export const FAILURE_LOGIN_USER = 'FAILURE_LOGIN_USER';

export const REQUEST_LOGOUT_USER = 'REQUEST_LOGOUT_USER';
export const SUCCESS_LOGOUT_USER = 'SUCCESS_LOGOUT_USER';
export const FAILURE_LOGOUT_USER = 'FAILURE_LOGOUT_USER';

export const REQUEST_SIGNUP_USER = 'REQUEST_SIGNUP_USER';
export const SUCCESS_SIGNUP_USER = 'SUCCESS_SIGNUP_USER';
export const FAILURE_SIGNUP_USER = 'FAILURE_SIGNUP_USER';


export const REQUEST_USER_PROFILE = 'REQUEST_USER_PROFILE';
export const SUCCESS_USER_PROFILE = 'SUCCESS_USER_PROFILE';
export const FAILURE_USER_PROFILE = 'FAILURE_USER_PROFILE';

export const REQUEST_ALL_RESTAURANTS = 'REQUEST_ALL_RESTAURANTS';
export const SUCCESS_ALL_RESTAURANTS = 'SUCCESS_ALL_RESTAURANTS';
export const FAILURE_ALL_RESTAURANTS = 'FAILURE_ALL_RESTAURANTS';

export const REQUEST_FILTER_RESTAURANTS = 'REQUEST_FILTER_RESTAURANTS';
export const SUCCESS_FILTER_RESTAURANTS = 'SUCCESS_FILTER_RESTAURANTS';
export const FAILURE_FILTER_RESTAURANTS = 'FAILURE_FILTER_RESTAURANTS';

export const REQUEST_NAME_RESTAURANTS = 'REQUEST_NAME_RESTAURANTS';
export const SUCCESS_NAME_RESTAURANTS = 'SUCCESS_NAME_RESTAURANTS';
export const FAILURE_NAME_RESTAURANTS = 'FAILURE_NAME_RESTAURANTS';

export const REQUEST_CREATE_COLLECTION = 'REQUEST_CREATE_COLLECTION';
export const SUCCESS_CREATE_COLLECTION = 'SUCCESS_CREATE_COLLECTION';
export const FAILURE_CREATE_COLLECTION = 'FAILURE_CREATE_COLLECTION';

export const REQUEST_ALL_COLLECTION = 'REQUEST_ALL_COLLECTION';
export const SUCCESS_ALL_COLLECTION = 'SUCCESS_ALL_COLLECTION';
export const FAILURE_ALL_COLLECTION = 'FAILURE_ALL_COLLECTION';

export const REQUEST_ADD_RESTAURANT_TO_COLLECTION = 'REQUEST_ADD_RESTAURANT_TO_COLLECTION';
export const SUCCESS_ADD_RESTAURANT_TO_COLLECTION = 'SUCCESS_ADD_RESTAURANT_TO_COLLECTION';
export const FAILURE_ADD_RESTAURANT_TO_COLLECTION = 'FAILURE_ADD_RESTAURANT_TO_COLLECTION';

export const REQUEST_GET_RESTAURANT_PARTOF_COLLECTION = 'REQUEST_GET_RESTAURANT_PARTOF_COLLECTION';
export const SUCCESS_GET_RESTAURANT_PARTOF_COLLECTION = 'SUCCESS_GET_RESTAURANT_PARTOF_COLLECTION';
export const FAILURE_GET_RESTAURANT_PARTOF_COLLECTION = 'FAILURE_GET_RESTAURANT_PARTOF_COLLECTION';

export const REQUEST_GET_RESTAURANTS_IN_COLLECTION = 'REQUEST_GET_RESTAURANTS_IN_COLLECTION';
export const SUCCESS_GET_RESTAURANTS_IN_COLLECTION = 'SUCCESS_GET_RESTAURANTS_IN_COLLECTION';
export const FAILURE_GET_RESTAURANTS_IN_COLLECTION = 'FAILURE_GET_RESTAURANTS_IN_COLLECTION';

export const REQUEST_DELETE_RESTAURANTS_IN_COLLECTION = 'REQUEST_DELETE_RESTAURANTS_IN_COLLECTION';
export const SUCCESS_DELETE_RESTAURANTS_IN_COLLECTION = 'SUCCESS_DELETE_RESTAURANTS_IN_COLLECTION';
export const FAILURE_DELETE_RESTAURANTS_IN_COLLECTION = 'FAILURE_DELETE_RESTAURANTS_IN_COLLECTION';

export const REQUEST_UPDATE_COLLECTION = 'REQUEST_UPDATE_COLLECTION';
export const SUCCESS_UPDATE_COLLECTION = 'SUCCESS_UPDATE_COLLECTION';
export const FAILURE_UPDATE_COLLECTION = 'FAILURE_UPDATE_COLLECTION';
